# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nana/biz/example/demo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nana/biz/example/demo.proto',
  package='nana.biz.example',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bnana/biz/example/demo.proto\x12\x10nana.biz.example\"\x1b\n\x0b\x44\x65moTimeReq\x12\x0c\n\x04time\x18\x01 \x01(\x03\"(\n\x0b\x44\x65moTimeRes\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x0b\n\x03\x63nt\x18\x02 \x01(\x05\"\x0e\n\x0c\x44\x65moCheckReq\"\x0e\n\x0c\x44\x65moCheckRes\"\x10\n\x0e\x44\x65moRestartReq\"\x10\n\x0e\x44\x65moRestartRes\"%\n\x07Request\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"$\n\x06Result\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c*\xbe\x01\n\tDemoSvrID\x12\x13\n\x0fSID_DEMO_UNKNOW\x10\x00\x12\x15\n\x11SID_DEMO_TIME_REQ\x10\x01\x12\x15\n\x11SID_DEMO_TIME_RES\x10\x02\x12\x1b\n\x16SID_DEMO_HEARTBEAT_REQ\x10\x81\x12\x12\x1b\n\x16SID_DEMO_HEARTBEAT_RES\x10\x82\x12\x12\x19\n\x14SID_DEMO_RESTART_REQ\x10\x83\x12\x12\x19\n\x14SID_DEMO_RESTART_RES\x10\x94\x01\x62\x06proto3')
)

_DEMOSVRID = _descriptor.EnumDescriptor(
  name='DemoSvrID',
  full_name='nana.biz.example.DemoSvrID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SID_DEMO_UNKNOW', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SID_DEMO_TIME_REQ', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SID_DEMO_TIME_RES', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SID_DEMO_HEARTBEAT_REQ', index=3, number=2305,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SID_DEMO_HEARTBEAT_RES', index=4, number=2306,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SID_DEMO_RESTART_REQ', index=5, number=2307,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SID_DEMO_RESTART_RES', index=6, number=148,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=266,
  serialized_end=456,
)
_sym_db.RegisterEnumDescriptor(_DEMOSVRID)

DemoSvrID = enum_type_wrapper.EnumTypeWrapper(_DEMOSVRID)
SID_DEMO_UNKNOW = 0
SID_DEMO_TIME_REQ = 1
SID_DEMO_TIME_RES = 2
SID_DEMO_HEARTBEAT_REQ = 2305
SID_DEMO_HEARTBEAT_RES = 2306
SID_DEMO_RESTART_REQ = 2307
SID_DEMO_RESTART_RES = 148



_DEMOTIMEREQ = _descriptor.Descriptor(
  name='DemoTimeReq',
  full_name='nana.biz.example.DemoTimeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='nana.biz.example.DemoTimeReq.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=76,
)


_DEMOTIMERES = _descriptor.Descriptor(
  name='DemoTimeRes',
  full_name='nana.biz.example.DemoTimeRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='nana.biz.example.DemoTimeRes.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cnt', full_name='nana.biz.example.DemoTimeRes.cnt', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=118,
)


_DEMOCHECKREQ = _descriptor.Descriptor(
  name='DemoCheckReq',
  full_name='nana.biz.example.DemoCheckReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=134,
)


_DEMOCHECKRES = _descriptor.Descriptor(
  name='DemoCheckRes',
  full_name='nana.biz.example.DemoCheckRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=150,
)


_DEMORESTARTREQ = _descriptor.Descriptor(
  name='DemoRestartReq',
  full_name='nana.biz.example.DemoRestartReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=168,
)


_DEMORESTARTRES = _descriptor.Descriptor(
  name='DemoRestartRes',
  full_name='nana.biz.example.DemoRestartRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=186,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='nana.biz.example.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='nana.biz.example.Request.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='nana.biz.example.Request.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=225,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='nana.biz.example.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='nana.biz.example.Result.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='nana.biz.example.Result.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=263,
)

DESCRIPTOR.message_types_by_name['DemoTimeReq'] = _DEMOTIMEREQ
DESCRIPTOR.message_types_by_name['DemoTimeRes'] = _DEMOTIMERES
DESCRIPTOR.message_types_by_name['DemoCheckReq'] = _DEMOCHECKREQ
DESCRIPTOR.message_types_by_name['DemoCheckRes'] = _DEMOCHECKRES
DESCRIPTOR.message_types_by_name['DemoRestartReq'] = _DEMORESTARTREQ
DESCRIPTOR.message_types_by_name['DemoRestartRes'] = _DEMORESTARTRES
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.enum_types_by_name['DemoSvrID'] = _DEMOSVRID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DemoTimeReq = _reflection.GeneratedProtocolMessageType('DemoTimeReq', (_message.Message,), dict(
  DESCRIPTOR = _DEMOTIMEREQ,
  __module__ = 'nana.biz.example.demo_pb2'
  # @@protoc_insertion_point(class_scope:nana.biz.example.DemoTimeReq)
  ))
_sym_db.RegisterMessage(DemoTimeReq)

DemoTimeRes = _reflection.GeneratedProtocolMessageType('DemoTimeRes', (_message.Message,), dict(
  DESCRIPTOR = _DEMOTIMERES,
  __module__ = 'nana.biz.example.demo_pb2'
  # @@protoc_insertion_point(class_scope:nana.biz.example.DemoTimeRes)
  ))
_sym_db.RegisterMessage(DemoTimeRes)

DemoCheckReq = _reflection.GeneratedProtocolMessageType('DemoCheckReq', (_message.Message,), dict(
  DESCRIPTOR = _DEMOCHECKREQ,
  __module__ = 'nana.biz.example.demo_pb2'
  # @@protoc_insertion_point(class_scope:nana.biz.example.DemoCheckReq)
  ))
_sym_db.RegisterMessage(DemoCheckReq)

DemoCheckRes = _reflection.GeneratedProtocolMessageType('DemoCheckRes', (_message.Message,), dict(
  DESCRIPTOR = _DEMOCHECKRES,
  __module__ = 'nana.biz.example.demo_pb2'
  # @@protoc_insertion_point(class_scope:nana.biz.example.DemoCheckRes)
  ))
_sym_db.RegisterMessage(DemoCheckRes)

DemoRestartReq = _reflection.GeneratedProtocolMessageType('DemoRestartReq', (_message.Message,), dict(
  DESCRIPTOR = _DEMORESTARTREQ,
  __module__ = 'nana.biz.example.demo_pb2'
  # @@protoc_insertion_point(class_scope:nana.biz.example.DemoRestartReq)
  ))
_sym_db.RegisterMessage(DemoRestartReq)

DemoRestartRes = _reflection.GeneratedProtocolMessageType('DemoRestartRes', (_message.Message,), dict(
  DESCRIPTOR = _DEMORESTARTRES,
  __module__ = 'nana.biz.example.demo_pb2'
  # @@protoc_insertion_point(class_scope:nana.biz.example.DemoRestartRes)
  ))
_sym_db.RegisterMessage(DemoRestartRes)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'nana.biz.example.demo_pb2'
  # @@protoc_insertion_point(class_scope:nana.biz.example.Request)
  ))
_sym_db.RegisterMessage(Request)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'nana.biz.example.demo_pb2'
  # @@protoc_insertion_point(class_scope:nana.biz.example.Result)
  ))
_sym_db.RegisterMessage(Result)


# @@protoc_insertion_point(module_scope)
