# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nana/esports/base.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nana/esports/base.proto',
  package='nana.esports',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17nana/esports/base.proto\x12\x0cnana.esports\"]\n\x05Timer\x12\x0f\n\x07ticking\x18\x01 \x01(\x05\x12\x11\n\tcountdown\x18\x02 \x01(\x05\x12\x0e\n\x06uptime\x18\x03 \x01(\x05\x12\x0e\n\x06second\x18\x04 \x01(\x05\x12\x10\n\x08\x61\x64\x64_time\x18\x05 \x01(\x05\x62\x06proto3')
)




_TIMER = _descriptor.Descriptor(
  name='Timer',
  full_name='nana.esports.Timer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticking', full_name='nana.esports.Timer.ticking', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='countdown', full_name='nana.esports.Timer.countdown', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uptime', full_name='nana.esports.Timer.uptime', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='second', full_name='nana.esports.Timer.second', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='add_time', full_name='nana.esports.Timer.add_time', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=134,
)

DESCRIPTOR.message_types_by_name['Timer'] = _TIMER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Timer = _reflection.GeneratedProtocolMessageType('Timer', (_message.Message,), dict(
  DESCRIPTOR = _TIMER,
  __module__ = 'nana.esports.base_pb2'
  # @@protoc_insertion_point(class_scope:nana.esports.Timer)
  ))
_sym_db.RegisterMessage(Timer)


# @@protoc_insertion_point(module_scope)
