# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nana/sports/base.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nana/sports/base.proto',
  package='nana.sports',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16nana/sports/base.proto\x12\x0bnana.sports\"?\n\x05Round\x12\x11\n\tgroup_num\x18\x01 \x01(\x05\x12\x11\n\tround_num\x18\x02 \x01(\x05\x12\x10\n\x08stage_id\x18\x03 \x01(\x05\"]\n\x05Timer\x12\x0f\n\x07ticking\x18\x01 \x01(\x05\x12\x11\n\tcountdown\x18\x02 \x01(\x05\x12\x0e\n\x06uptime\x18\x03 \x01(\x05\x12\x0e\n\x06second\x18\x04 \x01(\x05\x12\x10\n\x08\x61\x64\x64_time\x18\x05 \x01(\x05\"\x84\x01\n\x05Score\x12\x1f\n\x03tmr\x18\x01 \x01(\x0b\x32\x12.nana.sports.Timer\x12\x11\n\tstatus_id\x18\x02 \x01(\x05\x12\x13\n\x0bhome_scores\x18\x03 \x03(\x05\x12\x13\n\x0b\x61way_scores\x18\x04 \x03(\x05\x12\r\n\x05serve\x18\x05 \x01(\x05\x12\x0e\n\x06points\x18\x06 \x03(\t\"\xc0\x01\n\x05Stats\x12,\n\x05items\x18\x01 \x03(\x0b\x32\x1d.nana.sports.Stats.ItemsEntry\x1a\x42\n\x04Item\x12\x0c\n\x04home\x18\x01 \x01(\x05\x12\x0c\n\x04\x61way\x18\x02 \x01(\x05\x12\x0e\n\x06home_s\x18\x03 \x01(\t\x12\x0e\n\x06\x61way_s\x18\x04 \x01(\t\x1a\x45\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.nana.sports.Stats.Item:\x02\x38\x01\"+\n\x05Mlive\x12\n\n\x02vc\x18\x01 \x01(\t\x12\n\n\x02pg\x18\x02 \x01(\t\x12\n\n\x02xy\x18\x03 \x01(\tb\x06proto3')
)




_ROUND = _descriptor.Descriptor(
  name='Round',
  full_name='nana.sports.Round',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group_num', full_name='nana.sports.Round.group_num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='round_num', full_name='nana.sports.Round.round_num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stage_id', full_name='nana.sports.Round.stage_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=102,
)


_TIMER = _descriptor.Descriptor(
  name='Timer',
  full_name='nana.sports.Timer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticking', full_name='nana.sports.Timer.ticking', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='countdown', full_name='nana.sports.Timer.countdown', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uptime', full_name='nana.sports.Timer.uptime', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='second', full_name='nana.sports.Timer.second', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='add_time', full_name='nana.sports.Timer.add_time', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=197,
)


_SCORE = _descriptor.Descriptor(
  name='Score',
  full_name='nana.sports.Score',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tmr', full_name='nana.sports.Score.tmr', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status_id', full_name='nana.sports.Score.status_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='home_scores', full_name='nana.sports.Score.home_scores', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='away_scores', full_name='nana.sports.Score.away_scores', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serve', full_name='nana.sports.Score.serve', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='points', full_name='nana.sports.Score.points', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=332,
)


_STATS_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='nana.sports.Stats.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='home', full_name='nana.sports.Stats.Item.home', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='away', full_name='nana.sports.Stats.Item.away', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='home_s', full_name='nana.sports.Stats.Item.home_s', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='away_s', full_name='nana.sports.Stats.Item.away_s', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=390,
  serialized_end=456,
)

_STATS_ITEMSENTRY = _descriptor.Descriptor(
  name='ItemsEntry',
  full_name='nana.sports.Stats.ItemsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='nana.sports.Stats.ItemsEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='nana.sports.Stats.ItemsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=527,
)

_STATS = _descriptor.Descriptor(
  name='Stats',
  full_name='nana.sports.Stats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='nana.sports.Stats.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_STATS_ITEM, _STATS_ITEMSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=527,
)


_MLIVE = _descriptor.Descriptor(
  name='Mlive',
  full_name='nana.sports.Mlive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vc', full_name='nana.sports.Mlive.vc', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pg', full_name='nana.sports.Mlive.pg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='xy', full_name='nana.sports.Mlive.xy', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=529,
  serialized_end=572,
)

_SCORE.fields_by_name['tmr'].message_type = _TIMER
_STATS_ITEM.containing_type = _STATS
_STATS_ITEMSENTRY.fields_by_name['value'].message_type = _STATS_ITEM
_STATS_ITEMSENTRY.containing_type = _STATS
_STATS.fields_by_name['items'].message_type = _STATS_ITEMSENTRY
DESCRIPTOR.message_types_by_name['Round'] = _ROUND
DESCRIPTOR.message_types_by_name['Timer'] = _TIMER
DESCRIPTOR.message_types_by_name['Score'] = _SCORE
DESCRIPTOR.message_types_by_name['Stats'] = _STATS
DESCRIPTOR.message_types_by_name['Mlive'] = _MLIVE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Round = _reflection.GeneratedProtocolMessageType('Round', (_message.Message,), dict(
  DESCRIPTOR = _ROUND,
  __module__ = 'nana.sports.base_pb2'
  # @@protoc_insertion_point(class_scope:nana.sports.Round)
  ))
_sym_db.RegisterMessage(Round)

Timer = _reflection.GeneratedProtocolMessageType('Timer', (_message.Message,), dict(
  DESCRIPTOR = _TIMER,
  __module__ = 'nana.sports.base_pb2'
  # @@protoc_insertion_point(class_scope:nana.sports.Timer)
  ))
_sym_db.RegisterMessage(Timer)

Score = _reflection.GeneratedProtocolMessageType('Score', (_message.Message,), dict(
  DESCRIPTOR = _SCORE,
  __module__ = 'nana.sports.base_pb2'
  # @@protoc_insertion_point(class_scope:nana.sports.Score)
  ))
_sym_db.RegisterMessage(Score)

Stats = _reflection.GeneratedProtocolMessageType('Stats', (_message.Message,), dict(

  Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
    DESCRIPTOR = _STATS_ITEM,
    __module__ = 'nana.sports.base_pb2'
    # @@protoc_insertion_point(class_scope:nana.sports.Stats.Item)
    ))
  ,

  ItemsEntry = _reflection.GeneratedProtocolMessageType('ItemsEntry', (_message.Message,), dict(
    DESCRIPTOR = _STATS_ITEMSENTRY,
    __module__ = 'nana.sports.base_pb2'
    # @@protoc_insertion_point(class_scope:nana.sports.Stats.ItemsEntry)
    ))
  ,
  DESCRIPTOR = _STATS,
  __module__ = 'nana.sports.base_pb2'
  # @@protoc_insertion_point(class_scope:nana.sports.Stats)
  ))
_sym_db.RegisterMessage(Stats)
_sym_db.RegisterMessage(Stats.Item)
_sym_db.RegisterMessage(Stats.ItemsEntry)

Mlive = _reflection.GeneratedProtocolMessageType('Mlive', (_message.Message,), dict(
  DESCRIPTOR = _MLIVE,
  __module__ = 'nana.sports.base_pb2'
  # @@protoc_insertion_point(class_scope:nana.sports.Mlive)
  ))
_sym_db.RegisterMessage(Mlive)


_STATS_ITEMSENTRY._options = None
# @@protoc_insertion_point(module_scope)
