# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nana/sports/team_manager.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nana.sports import team_pb2 as nana_dot_sports_dot_team__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nana/sports/team_manager.proto',
  package='nana.sports',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1enana/sports/team_manager.proto\x12\x0bnana.sports\x1a\x16nana/sports/team.proto\"\xef\x01\n\x0bTeamManager\x12\x1f\n\x04team\x18\x01 \x01(\x0b\x32\x11.nana.sports.Team\x12\x32\n\x08managers\x18\x02 \x03(\x0b\x32 .nana.sports.TeamManager.Manager\x1a\x8a\x01\n\x07Manager\x12\x31\n\x07manager\x18\x01 \x01(\x0b\x32 .nana.sports.TeamManager.Manager\x12\x16\n\x0e\x61ppointed_time\x18\x02 \x01(\x05\x12\x16\n\x0e\x64ismissal_time\x18\x03 \x01(\x05\x12\x0f\n\x07matches\x18\x04 \x01(\x05\x12\x0b\n\x03ppg\x18\x05 \x01(\tb\x06proto3')
  ,
  dependencies=[nana_dot_sports_dot_team__pb2.DESCRIPTOR,])




_TEAMMANAGER_MANAGER = _descriptor.Descriptor(
  name='Manager',
  full_name='nana.sports.TeamManager.Manager',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='manager', full_name='nana.sports.TeamManager.Manager.manager', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='appointed_time', full_name='nana.sports.TeamManager.Manager.appointed_time', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dismissal_time', full_name='nana.sports.TeamManager.Manager.dismissal_time', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='matches', full_name='nana.sports.TeamManager.Manager.matches', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ppg', full_name='nana.sports.TeamManager.Manager.ppg', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=311,
)

_TEAMMANAGER = _descriptor.Descriptor(
  name='TeamManager',
  full_name='nana.sports.TeamManager',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='team', full_name='nana.sports.TeamManager.team', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='managers', full_name='nana.sports.TeamManager.managers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TEAMMANAGER_MANAGER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=311,
)

_TEAMMANAGER_MANAGER.fields_by_name['manager'].message_type = _TEAMMANAGER_MANAGER
_TEAMMANAGER_MANAGER.containing_type = _TEAMMANAGER
_TEAMMANAGER.fields_by_name['team'].message_type = nana_dot_sports_dot_team__pb2._TEAM
_TEAMMANAGER.fields_by_name['managers'].message_type = _TEAMMANAGER_MANAGER
DESCRIPTOR.message_types_by_name['TeamManager'] = _TEAMMANAGER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TeamManager = _reflection.GeneratedProtocolMessageType('TeamManager', (_message.Message,), dict(

  Manager = _reflection.GeneratedProtocolMessageType('Manager', (_message.Message,), dict(
    DESCRIPTOR = _TEAMMANAGER_MANAGER,
    __module__ = 'nana.sports.team_manager_pb2'
    # @@protoc_insertion_point(class_scope:nana.sports.TeamManager.Manager)
    ))
  ,
  DESCRIPTOR = _TEAMMANAGER,
  __module__ = 'nana.sports.team_manager_pb2'
  # @@protoc_insertion_point(class_scope:nana.sports.TeamManager)
  ))
_sym_db.RegisterMessage(TeamManager)
_sym_db.RegisterMessage(TeamManager.Manager)


# @@protoc_insertion_point(module_scope)
