# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nana/sports/football/match_trend.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nana/sports/football/match_trend.proto',
  package='nana.sports.football',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n&nana/sports/football/match_trend.proto\x12\x14nana.sports.football\"\xce\x01\n\nMatchTrend\x12\x0e\n\x06period\x18\x01 \x01(\x05\x12:\n\x05items\x18\x02 \x03(\x0b\x32+.nana.sports.football.MatchTrend.PeriodItem\x1a*\n\tItemValue\x12\x0e\n\x06minute\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\x1aH\n\nPeriodItem\x12:\n\x06values\x18\x01 \x03(\x0b\x32*.nana.sports.football.MatchTrend.ItemValueb\x06proto3')
)




_MATCHTREND_ITEMVALUE = _descriptor.Descriptor(
  name='ItemValue',
  full_name='nana.sports.football.MatchTrend.ItemValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='minute', full_name='nana.sports.football.MatchTrend.ItemValue.minute', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='nana.sports.football.MatchTrend.ItemValue.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=197,
)

_MATCHTREND_PERIODITEM = _descriptor.Descriptor(
  name='PeriodItem',
  full_name='nana.sports.football.MatchTrend.PeriodItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='nana.sports.football.MatchTrend.PeriodItem.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=271,
)

_MATCHTREND = _descriptor.Descriptor(
  name='MatchTrend',
  full_name='nana.sports.football.MatchTrend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='period', full_name='nana.sports.football.MatchTrend.period', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='items', full_name='nana.sports.football.MatchTrend.items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MATCHTREND_ITEMVALUE, _MATCHTREND_PERIODITEM, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=271,
)

_MATCHTREND_ITEMVALUE.containing_type = _MATCHTREND
_MATCHTREND_PERIODITEM.fields_by_name['values'].message_type = _MATCHTREND_ITEMVALUE
_MATCHTREND_PERIODITEM.containing_type = _MATCHTREND
_MATCHTREND.fields_by_name['items'].message_type = _MATCHTREND_PERIODITEM
DESCRIPTOR.message_types_by_name['MatchTrend'] = _MATCHTREND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MatchTrend = _reflection.GeneratedProtocolMessageType('MatchTrend', (_message.Message,), dict(

  ItemValue = _reflection.GeneratedProtocolMessageType('ItemValue', (_message.Message,), dict(
    DESCRIPTOR = _MATCHTREND_ITEMVALUE,
    __module__ = 'nana.sports.football.match_trend_pb2'
    # @@protoc_insertion_point(class_scope:nana.sports.football.MatchTrend.ItemValue)
    ))
  ,

  PeriodItem = _reflection.GeneratedProtocolMessageType('PeriodItem', (_message.Message,), dict(
    DESCRIPTOR = _MATCHTREND_PERIODITEM,
    __module__ = 'nana.sports.football.match_trend_pb2'
    # @@protoc_insertion_point(class_scope:nana.sports.football.MatchTrend.PeriodItem)
    ))
  ,
  DESCRIPTOR = _MATCHTREND,
  __module__ = 'nana.sports.football.match_trend_pb2'
  # @@protoc_insertion_point(class_scope:nana.sports.football.MatchTrend)
  ))
_sym_db.RegisterMessage(MatchTrend)
_sym_db.RegisterMessage(MatchTrend.ItemValue)
_sym_db.RegisterMessage(MatchTrend.PeriodItem)


# @@protoc_insertion_point(module_scope)
