# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nana/sports/football/match_incident.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nana/sports/football/match_incident.proto',
  package='nana.sports.football',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n)nana/sports/football/match_incident.proto\x12\x14nana.sports.football\"\x92\x04\n\rMatchIncident\x12\x37\n\x05items\x18\x01 \x03(\x0b\x32(.nana.sports.football.MatchIncident.Item\x1a\xc7\x03\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08sport_id\x18\x02 \x01(\x05\x12\x10\n\x08match_id\x18\x03 \x01(\x05\x12\x0f\n\x07team_id\x18\x04 \x01(\x05\x12\x0c\n\x04type\x18\x05 \x01(\x05\x12\x0e\n\x06second\x18\x06 \x01(\x05\x12\x0c\n\x04text\x18\x07 \x01(\t\x12\x0c\n\x04time\x18\x08 \x01(\t\x12\x0f\n\x07\x61\x64\x64time\x18\t \x01(\x05\x12\x0e\n\x06\x62\x65long\x18\n \x01(\x05\x12\x11\n\tplayer_id\x18\x0b \x01(\x05\x12\x13\n\x0bplayer_name\x18\x0c \x01(\t\x12\x12\n\nhome_score\x18\r \x01(\x05\x12\x12\n\naway_score\x18\x0e \x01(\x05\x12\x12\n\nassist1_id\x18\x0f \x01(\x05\x12\x14\n\x0c\x61ssist1_name\x18\x10 \x01(\t\x12\x12\n\nassist2_id\x18\x11 \x01(\x05\x12\x14\n\x0c\x61ssist2_name\x18\x12 \x01(\t\x12\x0e\n\x06reason\x18\x13 \x01(\t\x12\x14\n\x0cin_player_id\x18\x14 \x01(\x05\x12\x16\n\x0ein_player_name\x18\x15 \x01(\t\x12\x15\n\rout_player_id\x18\x16 \x01(\x05\x12\x17\n\x0fout_player_name\x18\x17 \x01(\t\x12\x11\n\tis_injury\x18\x18 \x01(\x05\x62\x06proto3')
)




_MATCHINCIDENT_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='nana.sports.football.MatchIncident.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='nana.sports.football.MatchIncident.Item.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sport_id', full_name='nana.sports.football.MatchIncident.Item.sport_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='match_id', full_name='nana.sports.football.MatchIncident.Item.match_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='team_id', full_name='nana.sports.football.MatchIncident.Item.team_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='nana.sports.football.MatchIncident.Item.type', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='second', full_name='nana.sports.football.MatchIncident.Item.second', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='nana.sports.football.MatchIncident.Item.text', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='nana.sports.football.MatchIncident.Item.time', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addtime', full_name='nana.sports.football.MatchIncident.Item.addtime', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='belong', full_name='nana.sports.football.MatchIncident.Item.belong', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_id', full_name='nana.sports.football.MatchIncident.Item.player_id', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_name', full_name='nana.sports.football.MatchIncident.Item.player_name', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='home_score', full_name='nana.sports.football.MatchIncident.Item.home_score', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='away_score', full_name='nana.sports.football.MatchIncident.Item.away_score', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='assist1_id', full_name='nana.sports.football.MatchIncident.Item.assist1_id', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='assist1_name', full_name='nana.sports.football.MatchIncident.Item.assist1_name', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='assist2_id', full_name='nana.sports.football.MatchIncident.Item.assist2_id', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='assist2_name', full_name='nana.sports.football.MatchIncident.Item.assist2_name', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reason', full_name='nana.sports.football.MatchIncident.Item.reason', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='in_player_id', full_name='nana.sports.football.MatchIncident.Item.in_player_id', index=19,
      number=20, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='in_player_name', full_name='nana.sports.football.MatchIncident.Item.in_player_name', index=20,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='out_player_id', full_name='nana.sports.football.MatchIncident.Item.out_player_id', index=21,
      number=22, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='out_player_name', full_name='nana.sports.football.MatchIncident.Item.out_player_name', index=22,
      number=23, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_injury', full_name='nana.sports.football.MatchIncident.Item.is_injury', index=23,
      number=24, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=598,
)

_MATCHINCIDENT = _descriptor.Descriptor(
  name='MatchIncident',
  full_name='nana.sports.football.MatchIncident',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='nana.sports.football.MatchIncident.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MATCHINCIDENT_ITEM, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=598,
)

_MATCHINCIDENT_ITEM.containing_type = _MATCHINCIDENT
_MATCHINCIDENT.fields_by_name['items'].message_type = _MATCHINCIDENT_ITEM
DESCRIPTOR.message_types_by_name['MatchIncident'] = _MATCHINCIDENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MatchIncident = _reflection.GeneratedProtocolMessageType('MatchIncident', (_message.Message,), dict(

  Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
    DESCRIPTOR = _MATCHINCIDENT_ITEM,
    __module__ = 'nana.sports.football.match_incident_pb2'
    # @@protoc_insertion_point(class_scope:nana.sports.football.MatchIncident.Item)
    ))
  ,
  DESCRIPTOR = _MATCHINCIDENT,
  __module__ = 'nana.sports.football.match_incident_pb2'
  # @@protoc_insertion_point(class_scope:nana.sports.football.MatchIncident)
  ))
_sym_db.RegisterMessage(MatchIncident)
_sym_db.RegisterMessage(MatchIncident.Item)


# @@protoc_insertion_point(module_scope)
