# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nana/sports/basketball/match_incident.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nana/sports/basketball/match_incident.proto',
  package='nana.sports.basketball',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n+nana/sports/basketball/match_incident.proto\x12\x16nana.sports.basketball\"\x8a\x03\n\x0f\x42kMatchIncident\x12\x0e\n\x06period\x18\x01 \x01(\x05\x12;\n\x05items\x18\x02 \x03(\x0b\x32,.nana.sports.basketball.BkMatchIncident.Item\x12\r\n\x05\x64\x65lta\x18\x03 \x01(\x08\x1a\x9a\x02\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x12\n\nhome_score\x18\x03 \x01(\x05\x12\x12\n\naway_score\x18\x04 \x01(\x05\x12\x0e\n\x06\x62\x65long\x18\x05 \x01(\x05\x12\x12\n\nplayer_ids\x18\x06 \x03(\x05\x12\x0e\n\x06period\x18\x07 \x01(\x05\x12\x13\n\x0bperiod_time\x18\x08 \x01(\t\x12\x12\n\nlocation_x\x18\t \x01(\x05\x12\x12\n\nlocation_y\x18\n \x01(\x05\x12\x15\n\rshooting_play\x18\x0b \x01(\x05\x12\x14\n\x0cscoring_play\x18\x0c \x01(\x05\x12\x13\n\x0bscore_value\x18\r \x01(\x05\x12\x0c\n\x04text\x18\x0e \x01(\t\x12\x0f\n\x07text_en\x18\x0f \x01(\tb\x06proto3')
)




_BKMATCHINCIDENT_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='nana.sports.basketball.BkMatchIncident.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='nana.sports.basketball.BkMatchIncident.Item.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='nana.sports.basketball.BkMatchIncident.Item.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='home_score', full_name='nana.sports.basketball.BkMatchIncident.Item.home_score', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='away_score', full_name='nana.sports.basketball.BkMatchIncident.Item.away_score', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='belong', full_name='nana.sports.basketball.BkMatchIncident.Item.belong', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_ids', full_name='nana.sports.basketball.BkMatchIncident.Item.player_ids', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='period', full_name='nana.sports.basketball.BkMatchIncident.Item.period', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='period_time', full_name='nana.sports.basketball.BkMatchIncident.Item.period_time', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location_x', full_name='nana.sports.basketball.BkMatchIncident.Item.location_x', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location_y', full_name='nana.sports.basketball.BkMatchIncident.Item.location_y', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shooting_play', full_name='nana.sports.basketball.BkMatchIncident.Item.shooting_play', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scoring_play', full_name='nana.sports.basketball.BkMatchIncident.Item.scoring_play', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score_value', full_name='nana.sports.basketball.BkMatchIncident.Item.score_value', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='nana.sports.basketball.BkMatchIncident.Item.text', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text_en', full_name='nana.sports.basketball.BkMatchIncident.Item.text_en', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=466,
)

_BKMATCHINCIDENT = _descriptor.Descriptor(
  name='BkMatchIncident',
  full_name='nana.sports.basketball.BkMatchIncident',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='period', full_name='nana.sports.basketball.BkMatchIncident.period', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='items', full_name='nana.sports.basketball.BkMatchIncident.items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delta', full_name='nana.sports.basketball.BkMatchIncident.delta', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BKMATCHINCIDENT_ITEM, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=466,
)

_BKMATCHINCIDENT_ITEM.containing_type = _BKMATCHINCIDENT
_BKMATCHINCIDENT.fields_by_name['items'].message_type = _BKMATCHINCIDENT_ITEM
DESCRIPTOR.message_types_by_name['BkMatchIncident'] = _BKMATCHINCIDENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BkMatchIncident = _reflection.GeneratedProtocolMessageType('BkMatchIncident', (_message.Message,), dict(

  Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
    DESCRIPTOR = _BKMATCHINCIDENT_ITEM,
    __module__ = 'nana.sports.basketball.match_incident_pb2'
    # @@protoc_insertion_point(class_scope:nana.sports.basketball.BkMatchIncident.Item)
    ))
  ,
  DESCRIPTOR = _BKMATCHINCIDENT,
  __module__ = 'nana.sports.basketball.match_incident_pb2'
  # @@protoc_insertion_point(class_scope:nana.sports.basketball.BkMatchIncident)
  ))
_sym_db.RegisterMessage(BkMatchIncident)
_sym_db.RegisterMessage(BkMatchIncident.Item)


# @@protoc_insertion_point(module_scope)
