# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nana/sports/feed.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nana/sports/feed.proto',
  package='nana.sports',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16nana/sports/feed.proto\x12\x0bnana.sports\"?\n\x07\x46\x65\x65\x64Req\x12&\n\x04type\x18\x01 \x01(\x0e\x32\x18.nana.sports.FeedMsgType\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"w\n\x07\x46\x65\x65\x64Rsp\x12,\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1e.nana.sports.FeedRsp.ErrorCode\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"0\n\tErrorCode\x12\n\n\x06SUCESS\x10\x00\x12\x0c\n\x08Internal\x10\x01\x12\t\n\x05\x42lock\x10\x02\"L\n\x0cMatchInfoReq\x12\x11\n\tmatch_ids\x18\x01 \x03(\x05\x12\x13\n\x0bneed_resend\x18\x02 \x01(\x08\x12\x14\n\x0cneed_restart\x18\x03 \x01(\x08\"\x0e\n\x0cMatchInfoRsp\";\n\x0eMatchInplayReq\x12\x13\n\x0bneed_resend\x18\x02 \x01(\x08\x12\x14\n\x0cneed_restart\x18\x03 \x01(\x08\"\x10\n\x0eMatchInplayRsp*|\n\x0b\x46\x65\x65\x64MsgType\x12\x0f\n\x0b\x46\x45\x45\x44_UNKNOW\x10\x00\x12\x17\n\x12MATCH_INFO_RESTART\x10\x81 \x12\x17\n\x12MATCH_LIVE_RESTART\x10\x82 \x12\x15\n\x10MATCH_INPLAY_REQ\x10\x83 \x12\x13\n\x0eMATCH_INFO_REQ\x10\x84 b\x06proto3')
)

_FEEDMSGTYPE = _descriptor.EnumDescriptor(
  name='FeedMsgType',
  full_name='nana.sports.FeedMsgType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FEED_UNKNOW', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MATCH_INFO_RESTART', index=1, number=4097,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MATCH_LIVE_RESTART', index=2, number=4098,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MATCH_INPLAY_REQ', index=3, number=4099,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MATCH_INFO_REQ', index=4, number=4100,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=398,
  serialized_end=522,
)
_sym_db.RegisterEnumDescriptor(_FEEDMSGTYPE)

FeedMsgType = enum_type_wrapper.EnumTypeWrapper(_FEEDMSGTYPE)
FEED_UNKNOW = 0
MATCH_INFO_RESTART = 4097
MATCH_LIVE_RESTART = 4098
MATCH_INPLAY_REQ = 4099
MATCH_INFO_REQ = 4100


_FEEDRSP_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='nana.sports.FeedRsp.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Internal', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Block', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=175,
  serialized_end=223,
)
_sym_db.RegisterEnumDescriptor(_FEEDRSP_ERRORCODE)


_FEEDREQ = _descriptor.Descriptor(
  name='FeedReq',
  full_name='nana.sports.FeedReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='nana.sports.FeedReq.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='nana.sports.FeedReq.data', index=1,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=102,
)


_FEEDRSP = _descriptor.Descriptor(
  name='FeedRsp',
  full_name='nana.sports.FeedRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='nana.sports.FeedRsp.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='nana.sports.FeedRsp.data', index=1,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FEEDRSP_ERRORCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=223,
)


_MATCHINFOREQ = _descriptor.Descriptor(
  name='MatchInfoReq',
  full_name='nana.sports.MatchInfoReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='match_ids', full_name='nana.sports.MatchInfoReq.match_ids', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='need_resend', full_name='nana.sports.MatchInfoReq.need_resend', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='need_restart', full_name='nana.sports.MatchInfoReq.need_restart', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=301,
)


_MATCHINFORSP = _descriptor.Descriptor(
  name='MatchInfoRsp',
  full_name='nana.sports.MatchInfoRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=317,
)


_MATCHINPLAYREQ = _descriptor.Descriptor(
  name='MatchInplayReq',
  full_name='nana.sports.MatchInplayReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='need_resend', full_name='nana.sports.MatchInplayReq.need_resend', index=0,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='need_restart', full_name='nana.sports.MatchInplayReq.need_restart', index=1,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=378,
)


_MATCHINPLAYRSP = _descriptor.Descriptor(
  name='MatchInplayRsp',
  full_name='nana.sports.MatchInplayRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=396,
)

_FEEDREQ.fields_by_name['type'].enum_type = _FEEDMSGTYPE
_FEEDRSP.fields_by_name['code'].enum_type = _FEEDRSP_ERRORCODE
_FEEDRSP_ERRORCODE.containing_type = _FEEDRSP
DESCRIPTOR.message_types_by_name['FeedReq'] = _FEEDREQ
DESCRIPTOR.message_types_by_name['FeedRsp'] = _FEEDRSP
DESCRIPTOR.message_types_by_name['MatchInfoReq'] = _MATCHINFOREQ
DESCRIPTOR.message_types_by_name['MatchInfoRsp'] = _MATCHINFORSP
DESCRIPTOR.message_types_by_name['MatchInplayReq'] = _MATCHINPLAYREQ
DESCRIPTOR.message_types_by_name['MatchInplayRsp'] = _MATCHINPLAYRSP
DESCRIPTOR.enum_types_by_name['FeedMsgType'] = _FEEDMSGTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FeedReq = _reflection.GeneratedProtocolMessageType('FeedReq', (_message.Message,), dict(
  DESCRIPTOR = _FEEDREQ,
  __module__ = 'nana.sports.feed_pb2'
  # @@protoc_insertion_point(class_scope:nana.sports.FeedReq)
  ))
_sym_db.RegisterMessage(FeedReq)

FeedRsp = _reflection.GeneratedProtocolMessageType('FeedRsp', (_message.Message,), dict(
  DESCRIPTOR = _FEEDRSP,
  __module__ = 'nana.sports.feed_pb2'
  # @@protoc_insertion_point(class_scope:nana.sports.FeedRsp)
  ))
_sym_db.RegisterMessage(FeedRsp)

MatchInfoReq = _reflection.GeneratedProtocolMessageType('MatchInfoReq', (_message.Message,), dict(
  DESCRIPTOR = _MATCHINFOREQ,
  __module__ = 'nana.sports.feed_pb2'
  # @@protoc_insertion_point(class_scope:nana.sports.MatchInfoReq)
  ))
_sym_db.RegisterMessage(MatchInfoReq)

MatchInfoRsp = _reflection.GeneratedProtocolMessageType('MatchInfoRsp', (_message.Message,), dict(
  DESCRIPTOR = _MATCHINFORSP,
  __module__ = 'nana.sports.feed_pb2'
  # @@protoc_insertion_point(class_scope:nana.sports.MatchInfoRsp)
  ))
_sym_db.RegisterMessage(MatchInfoRsp)

MatchInplayReq = _reflection.GeneratedProtocolMessageType('MatchInplayReq', (_message.Message,), dict(
  DESCRIPTOR = _MATCHINPLAYREQ,
  __module__ = 'nana.sports.feed_pb2'
  # @@protoc_insertion_point(class_scope:nana.sports.MatchInplayReq)
  ))
_sym_db.RegisterMessage(MatchInplayReq)

MatchInplayRsp = _reflection.GeneratedProtocolMessageType('MatchInplayRsp', (_message.Message,), dict(
  DESCRIPTOR = _MATCHINPLAYRSP,
  __module__ = 'nana.sports.feed_pb2'
  # @@protoc_insertion_point(class_scope:nana.sports.MatchInplayRsp)
  ))
_sym_db.RegisterMessage(MatchInplayRsp)


# @@protoc_insertion_point(module_scope)
