# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nana/sports/honor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nana/sports/honor.proto',
  package='nana.sports',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17nana/sports/honor.proto\x12\x0bnana.sports\"k\n\x05Honor\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x08sport_id\x18\x02 \x01(\r\x12\x10\n\x08title_en\x18\x03 \x01(\t\x12\x10\n\x08title_zh\x18\x04 \x01(\t\x12\x11\n\ttitle_zht\x18\x05 \x01(\t\x12\r\n\x05\x65xtra\x18\x0f \x01(\x0c\"k\n\x05Title\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x08sport_id\x18\x02 \x01(\r\x12\x10\n\x08title_en\x18\x03 \x01(\t\x12\x10\n\x08title_zh\x18\x04 \x01(\t\x12\x11\n\ttitle_zht\x18\x05 \x01(\t\x12\r\n\x05\x65xtra\x18\x0f \x01(\x0c\x62\x06proto3')
)




_HONOR = _descriptor.Descriptor(
  name='Honor',
  full_name='nana.sports.Honor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='nana.sports.Honor.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sport_id', full_name='nana.sports.Honor.sport_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title_en', full_name='nana.sports.Honor.title_en', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title_zh', full_name='nana.sports.Honor.title_zh', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title_zht', full_name='nana.sports.Honor.title_zht', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extra', full_name='nana.sports.Honor.extra', index=5,
      number=15, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=147,
)


_TITLE = _descriptor.Descriptor(
  name='Title',
  full_name='nana.sports.Title',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='nana.sports.Title.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sport_id', full_name='nana.sports.Title.sport_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title_en', full_name='nana.sports.Title.title_en', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title_zh', full_name='nana.sports.Title.title_zh', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title_zht', full_name='nana.sports.Title.title_zht', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extra', full_name='nana.sports.Title.extra', index=5,
      number=15, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=256,
)

DESCRIPTOR.message_types_by_name['Honor'] = _HONOR
DESCRIPTOR.message_types_by_name['Title'] = _TITLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Honor = _reflection.GeneratedProtocolMessageType('Honor', (_message.Message,), dict(
  DESCRIPTOR = _HONOR,
  __module__ = 'nana.sports.honor_pb2'
  # @@protoc_insertion_point(class_scope:nana.sports.Honor)
  ))
_sym_db.RegisterMessage(Honor)

Title = _reflection.GeneratedProtocolMessageType('Title', (_message.Message,), dict(
  DESCRIPTOR = _TITLE,
  __module__ = 'nana.sports.honor_pb2'
  # @@protoc_insertion_point(class_scope:nana.sports.Title)
  ))
_sym_db.RegisterMessage(Title)


# @@protoc_insertion_point(module_scope)
