# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nana/sports/player_honor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nana.sports import season_pb2 as nana_dot_sports_dot_season__pb2
from nana.sports import comp_pb2 as nana_dot_sports_dot_comp__pb2
from nana.sports import honor_pb2 as nana_dot_sports_dot_honor__pb2
from nana.sports import team_pb2 as nana_dot_sports_dot_team__pb2
from nana.sports import player_pb2 as nana_dot_sports_dot_player__pb2
from nana.sports import country_pb2 as nana_dot_sports_dot_country__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nana/sports/player_honor.proto',
  package='nana.sports',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1enana/sports/player_honor.proto\x12\x0bnana.sports\x1a\x18nana/sports/season.proto\x1a\x16nana/sports/comp.proto\x1a\x17nana/sports/honor.proto\x1a\x16nana/sports/team.proto\x1a\x18nana/sports/nbl_player.proto\x1a\x19nana/sports/country.proto\"\xcc\x02\n\x0bPlayerHonor\x12#\n\x06player\x18\x01 \x01(\x0b\x32\x13.nana.sports.Player\x12.\n\x06honors\x18\x02 \x03(\x0b\x32\x1e.nana.sports.PlayerHonor.Honor\x1a\xe7\x01\n\x05Honor\x12-\n\x05honor\x18\x01 \x01(\x0b\x32\x1e.nana.sports.PlayerHonor.Honor\x12\x1f\n\x04team\x18\x02 \x01(\x0b\x32\x11.nana.sports.Team\x12\x1f\n\x04\x63omp\x18\x03 \x01(\x0b\x32\x11.nana.sports.Comp\x12#\n\x06season\x18\x04 \x01(\x0b\x32\x13.nana.sports.Season\x12%\n\x07\x63ountry\x18\x05 \x01(\x0b\x32\x14.nana.sports.Country\x12!\n\x05title\x18\x06 \x01(\x0b\x32\x12.nana.sports.Titleb\x06proto3')
  ,
  dependencies=[nana_dot_sports_dot_season__pb2.DESCRIPTOR,nana_dot_sports_dot_comp__pb2.DESCRIPTOR,nana_dot_sports_dot_honor__pb2.DESCRIPTOR,nana_dot_sports_dot_team__pb2.DESCRIPTOR,nana_dot_sports_dot_player__pb2.DESCRIPTOR,nana_dot_sports_dot_country__pb2.DESCRIPTOR,])




_PLAYERHONOR_HONOR = _descriptor.Descriptor(
  name='Honor',
  full_name='nana.sports.PlayerHonor.Honor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='honor', full_name='nana.sports.PlayerHonor.Honor.honor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='team', full_name='nana.sports.PlayerHonor.Honor.team', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comp', full_name='nana.sports.PlayerHonor.Honor.comp', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='season', full_name='nana.sports.PlayerHonor.Honor.season', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='country', full_name='nana.sports.PlayerHonor.Honor.country', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='nana.sports.PlayerHonor.Honor.title', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=532,
)

_PLAYERHONOR = _descriptor.Descriptor(
  name='PlayerHonor',
  full_name='nana.sports.PlayerHonor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nbl_player', full_name='nana.sports.PlayerHonor.nbl_player', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='honors', full_name='nana.sports.PlayerHonor.honors', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PLAYERHONOR_HONOR, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=532,
)

_PLAYERHONOR_HONOR.fields_by_name['honor'].message_type = _PLAYERHONOR_HONOR
_PLAYERHONOR_HONOR.fields_by_name['team'].message_type = nana_dot_sports_dot_team__pb2._TEAM
_PLAYERHONOR_HONOR.fields_by_name['comp'].message_type = nana_dot_sports_dot_comp__pb2._COMP
_PLAYERHONOR_HONOR.fields_by_name['season'].message_type = nana_dot_sports_dot_season__pb2._SEASON
_PLAYERHONOR_HONOR.fields_by_name['country'].message_type = nana_dot_sports_dot_country__pb2._COUNTRY
_PLAYERHONOR_HONOR.fields_by_name['title'].message_type = nana_dot_sports_dot_honor__pb2._TITLE
_PLAYERHONOR_HONOR.containing_type = _PLAYERHONOR
_PLAYERHONOR.fields_by_name['nbl_player'].message_type = nana_dot_sports_dot_player__pb2._PLAYER
_PLAYERHONOR.fields_by_name['honors'].message_type = _PLAYERHONOR_HONOR
DESCRIPTOR.message_types_by_name['PlayerHonor'] = _PLAYERHONOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerHonor = _reflection.GeneratedProtocolMessageType('PlayerHonor', (_message.Message,), dict(

  Honor = _reflection.GeneratedProtocolMessageType('Honor', (_message.Message,), dict(
    DESCRIPTOR = _PLAYERHONOR_HONOR,
    __module__ = 'nana.sports.player_honor_pb2'
    # @@protoc_insertion_point(class_scope:nana.sports.PlayerHonor.Honor)
    ))
  ,
  DESCRIPTOR = _PLAYERHONOR,
  __module__ = 'nana.sports.player_honor_pb2'
  # @@protoc_insertion_point(class_scope:nana.sports.PlayerHonor)
  ))
_sym_db.RegisterMessage(PlayerHonor)
_sym_db.RegisterMessage(PlayerHonor.Honor)


# @@protoc_insertion_point(module_scope)
