# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nana/sports/team_squad.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nana.sports import season_pb2 as nana_dot_sports_dot_season__pb2
from nana.sports import team_pb2 as nana_dot_sports_dot_team__pb2
from nana.sports import player_pb2 as nana_dot_sports_dot_player__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nana/sports/team_squad.proto',
  package='nana.sports',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1cnana/sports/team_squad.proto\x12\x0bnana.sports\x1a\x18nana/sports/season.proto\x1a\x16nana/sports/team.proto\x1a\x18nana/sports/player_img.proto\"\x80\x02\n\tTeamSquad\x12#\n\x06season\x18\x01 \x01(\x0b\x32\x13.nana.sports.Season\x12\x1f\n\x04team\x18\x02 \x01(\x0b\x32\x11.nana.sports.Team\x12$\n\x07players\x18\x03 \x03(\x0b\x32\x13.nana.sports.Player\x1a\x86\x01\n\nTeamPlayer\x12#\n\x06player\x18\x01 \x01(\x0b\x32\x13.nana.sports.Player\x12\x10\n\x08position\x18\x02 \x01(\t\x12\x17\n\x0f\x64\x65tail_position\x18\x03 \x01(\t\x12\x14\n\x0cshirt_number\x18\x04 \x01(\t\x12\x12\n\nis_captain\x18\x05 \x01(\x05\x62\x06proto3')
  ,
  dependencies=[nana_dot_sports_dot_season__pb2.DESCRIPTOR,nana_dot_sports_dot_team__pb2.DESCRIPTOR,nana_dot_sports_dot_player__pb2.DESCRIPTOR,])




_TEAMSQUAD_TEAMPLAYER = _descriptor.Descriptor(
  name='TeamPlayer',
  full_name='nana.sports.TeamSquad.TeamPlayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_img', full_name='nana.sports.TeamSquad.TeamPlayer.player_img', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='nana.sports.TeamSquad.TeamPlayer.position', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detail_position', full_name='nana.sports.TeamSquad.TeamPlayer.detail_position', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shirt_number', full_name='nana.sports.TeamSquad.TeamPlayer.shirt_number', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_captain', full_name='nana.sports.TeamSquad.TeamPlayer.is_captain', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=378,
)

_TEAMSQUAD = _descriptor.Descriptor(
  name='TeamSquad',
  full_name='nana.sports.TeamSquad',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='season', full_name='nana.sports.TeamSquad.season', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='team', full_name='nana.sports.TeamSquad.team', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='players', full_name='nana.sports.TeamSquad.players', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TEAMSQUAD_TEAMPLAYER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=378,
)

_TEAMSQUAD_TEAMPLAYER.fields_by_name['player_img'].message_type = nana_dot_sports_dot_player__pb2._PLAYER
_TEAMSQUAD_TEAMPLAYER.containing_type = _TEAMSQUAD
_TEAMSQUAD.fields_by_name['season'].message_type = nana_dot_sports_dot_season__pb2._SEASON
_TEAMSQUAD.fields_by_name['team'].message_type = nana_dot_sports_dot_team__pb2._TEAM
_TEAMSQUAD.fields_by_name['players'].message_type = nana_dot_sports_dot_player__pb2._PLAYER
DESCRIPTOR.message_types_by_name['TeamSquad'] = _TEAMSQUAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TeamSquad = _reflection.GeneratedProtocolMessageType('TeamSquad', (_message.Message,), dict(

  TeamPlayer = _reflection.GeneratedProtocolMessageType('TeamPlayer', (_message.Message,), dict(
    DESCRIPTOR = _TEAMSQUAD_TEAMPLAYER,
    __module__ = 'nana.sports.team_squad_pb2'
    # @@protoc_insertion_point(class_scope:nana.sports.TeamSquad.TeamPlayer)
    ))
  ,
  DESCRIPTOR = _TEAMSQUAD,
  __module__ = 'nana.sports.team_squad_pb2'
  # @@protoc_insertion_point(class_scope:nana.sports.TeamSquad)
  ))
_sym_db.RegisterMessage(TeamSquad)
_sym_db.RegisterMessage(TeamSquad.TeamPlayer)


# @@protoc_insertion_point(module_scope)
