# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nana/sports/team_injury.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nana/sports/team_injury.proto',
  package='nana.sports',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1dnana/sports/team_injury.proto\x12\x0bnana.sports\"\xdb\x01\n\nTeamInjury\x12/\n\x07players\x18\x02 \x03(\x0b\x32\x1e.nana.sports.TeamInjury.Player\x1a\x9b\x01\n\x06Player\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63omp_id\x18\x02 \x01(\t\x12\x0f\n\x07team_id\x18\x03 \x01(\x05\x12\x0c\n\x04type\x18\x04 \x01(\x05\x12\x10\n\x08reson_en\x18\x05 \x01(\t\x12\x12\n\nstart_time\x18\x06 \x01(\x05\x12\x10\n\x08\x65nd_time\x18\x07 \x01(\x05\x12\x16\n\x0emissed_matches\x18\x08 \x01(\x05\x62\x06proto3')
)




_TEAMINJURY_PLAYER = _descriptor.Descriptor(
  name='Player',
  full_name='nana.sports.TeamInjury.Player',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_id', full_name='nana.sports.TeamInjury.Player.player_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comp_id', full_name='nana.sports.TeamInjury.Player.comp_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='team_id', full_name='nana.sports.TeamInjury.Player.team_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='nana.sports.TeamInjury.Player.type', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reson_en', full_name='nana.sports.TeamInjury.Player.reson_en', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='nana.sports.TeamInjury.Player.start_time', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='nana.sports.TeamInjury.Player.end_time', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='missed_matches', full_name='nana.sports.TeamInjury.Player.missed_matches', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=266,
)

_TEAMINJURY = _descriptor.Descriptor(
  name='TeamInjury',
  full_name='nana.sports.TeamInjury',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='players', full_name='nana.sports.TeamInjury.players', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TEAMINJURY_PLAYER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=266,
)

_TEAMINJURY_PLAYER.containing_type = _TEAMINJURY
_TEAMINJURY.fields_by_name['players'].message_type = _TEAMINJURY_PLAYER
DESCRIPTOR.message_types_by_name['TeamInjury'] = _TEAMINJURY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TeamInjury = _reflection.GeneratedProtocolMessageType('TeamInjury', (_message.Message,), dict(

  Player = _reflection.GeneratedProtocolMessageType('Player', (_message.Message,), dict(
    DESCRIPTOR = _TEAMINJURY_PLAYER,
    __module__ = 'nana.sports.team_injury_pb2'
    # @@protoc_insertion_point(class_scope:nana.sports.TeamInjury.Player)
    ))
  ,
  DESCRIPTOR = _TEAMINJURY,
  __module__ = 'nana.sports.team_injury_pb2'
  # @@protoc_insertion_point(class_scope:nana.sports.TeamInjury)
  ))
_sym_db.RegisterMessage(TeamInjury)
_sym_db.RegisterMessage(TeamInjury.Player)


# @@protoc_insertion_point(module_scope)
