# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nana/biz/japan_ball/match.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nana.sports import match_pb2 as nana_dot_sports_dot_match__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nana/biz/japan_ball/match.proto',
  package='nana.biz.fiba',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1fnana/biz/japan_ball/match.proto\x12\rnana.biz.fiba\x1a\x17nana/sports/match.proto\"?\n\x0c\x46ibaMatchReq\x12\x0c\n\x04time\x18\x08 \x01(\x03\x12!\n\x05match\x18\x02 \x01(\x0b\x32\x12.nana.sports.Match\"?\n\x0c\x46ibaMatchRes\x12\x0c\n\x04\x63ode\x18\x08 \x01(\x03\x12!\n\x05match\x18\x02 \x01(\x0b\x32\x12.nana.sports.Match\"%\n\x07Request\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"$\n\x06Result\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c*\x94\x02\n\x0e\x46ibaMatchSvrID\x12\x18\n\x14SID_FIBAMATCH_UNKNOW\x10\x00\x12\x1a\n\x16SID_FIBAMATCH_TIME_REQ\x10\x01\x12\x1a\n\x16SID_FIBAMATCH_TIME_RES\x10\x02\x12 \n\x1bSID_FIBAMATCH_HEARTBEAT_REQ\x10\x81\x12\x12 \n\x1bSID_FIBAMATCH_HEARTBEAT_RES\x10\x82\x12\x12\x1e\n\x19SID_FIBAMATCH_RESTART_REQ\x10\x83\x12\x12\x1e\n\x19SID_FIBAMATCH_RESTART_RES\x10\x94\x01\x12\x15\n\x11SID_FIBAMATCH_REQ\x10\x10\x12\x15\n\x11SID_FIBAMATCH_RES\x10\x11\x62\x06proto3')
  ,
  dependencies=[nana_dot_sports_dot_match__pb2.DESCRIPTOR,])

_FIBAMATCHSVRID = _descriptor.EnumDescriptor(
  name='FibaMatchSvrID',
  full_name='nana.biz.fiba.FibaMatchSvrID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SID_FIBAMATCH_UNKNOW', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SID_FIBAMATCH_TIME_REQ', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SID_FIBAMATCH_TIME_RES', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SID_FIBAMATCH_HEARTBEAT_REQ', index=3, number=2305,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SID_FIBAMATCH_HEARTBEAT_RES', index=4, number=2306,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SID_FIBAMATCH_RESTART_REQ', index=5, number=2307,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SID_FIBAMATCH_RESTART_RES', index=6, number=148,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SID_FIBAMATCH_REQ', index=7, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SID_FIBAMATCH_RES', index=8, number=17,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=283,
  serialized_end=559,
)
_sym_db.RegisterEnumDescriptor(_FIBAMATCHSVRID)

FibaMatchSvrID = enum_type_wrapper.EnumTypeWrapper(_FIBAMATCHSVRID)
SID_FIBAMATCH_UNKNOW = 0
SID_FIBAMATCH_TIME_REQ = 1
SID_FIBAMATCH_TIME_RES = 2
SID_FIBAMATCH_HEARTBEAT_REQ = 2305
SID_FIBAMATCH_HEARTBEAT_RES = 2306
SID_FIBAMATCH_RESTART_REQ = 2307
SID_FIBAMATCH_RESTART_RES = 148
SID_FIBAMATCH_REQ = 16
SID_FIBAMATCH_RES = 17



_FIBAMATCHREQ = _descriptor.Descriptor(
  name='FibaMatchReq',
  full_name='nana.biz.fiba.FibaMatchReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='nana.biz.fiba.FibaMatchReq.time', index=0,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='match', full_name='nana.biz.fiba.FibaMatchReq.match', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=138,
)


_FIBAMATCHRES = _descriptor.Descriptor(
  name='FibaMatchRes',
  full_name='nana.biz.fiba.FibaMatchRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='nana.biz.fiba.FibaMatchRes.code', index=0,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='match', full_name='nana.biz.fiba.FibaMatchRes.match', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=203,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='nana.biz.fiba.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='nana.biz.fiba.Request.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='nana.biz.fiba.Request.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=242,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='nana.biz.fiba.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='nana.biz.fiba.Result.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='nana.biz.fiba.Result.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=280,
)

_FIBAMATCHREQ.fields_by_name['match'].message_type = nana_dot_sports_dot_match__pb2._MATCH
_FIBAMATCHRES.fields_by_name['match'].message_type = nana_dot_sports_dot_match__pb2._MATCH
DESCRIPTOR.message_types_by_name['FibaMatchReq'] = _FIBAMATCHREQ
DESCRIPTOR.message_types_by_name['FibaMatchRes'] = _FIBAMATCHRES
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.enum_types_by_name['FibaMatchSvrID'] = _FIBAMATCHSVRID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FibaMatchReq = _reflection.GeneratedProtocolMessageType('FibaMatchReq', (_message.Message,), dict(
  DESCRIPTOR = _FIBAMATCHREQ,
  __module__ = 'nana.biz.japan_ball.match_pb2'
  # @@protoc_insertion_point(class_scope:nana.biz.fiba.FibaMatchReq)
  ))
_sym_db.RegisterMessage(FibaMatchReq)

FibaMatchRes = _reflection.GeneratedProtocolMessageType('FibaMatchRes', (_message.Message,), dict(
  DESCRIPTOR = _FIBAMATCHRES,
  __module__ = 'nana.biz.japan_ball.match_pb2'
  # @@protoc_insertion_point(class_scope:nana.biz.fiba.FibaMatchRes)
  ))
_sym_db.RegisterMessage(FibaMatchRes)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'nana.biz.japan_ball.match_pb2'
  # @@protoc_insertion_point(class_scope:nana.biz.fiba.Request)
  ))
_sym_db.RegisterMessage(Request)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'nana.biz.japan_ball.match_pb2'
  # @@protoc_insertion_point(class_scope:nana.biz.fiba.Result)
  ))
_sym_db.RegisterMessage(Result)


# @@protoc_insertion_point(module_scope)
