# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nana/biz/lol/match.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nana.esports.lol import match_pb2 as nana_dot_esports_dot_lol_dot_match__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nana/biz/lol/match.proto',
  package='nana.biz.lol',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18nana/biz/lol/match.proto\x12\x0cnana.biz.lol\x1a\x1cnana/esports/lol/match.proto\"F\n\x0bLolMatchReq\x12\x0c\n\x04time\x18\x08 \x01(\x03\x12)\n\x05match\x18\x02 \x01(\x0b\x32\x1a.nana.esports.lol.LolMatch\"F\n\x0bLolMatchRes\x12\x0c\n\x04\x63ode\x18\x08 \x01(\x05\x12)\n\x05match\x18\x02 \x01(\x0b\x32\x1a.nana.esports.lol.LolMatch\"%\n\x07Request\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"$\n\x06Result\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c*\xdb\x01\n\rLolMatchSvrID\x12\x18\n\x14SID_LOL_MATCH_UNKNOW\x10\x00\x12 \n\x1bSID_LOL_MATCH_HEARTBEAT_REQ\x10\x81\x12\x12 \n\x1bSID_LOL_MATCH_HEARTBEAT_RES\x10\x82\x12\x12\x1e\n\x19SID_LOL_MATCH_RESTART_REQ\x10\x83\x12\x12\x1e\n\x19SID_LOL_MATCH_RESTART_RES\x10\x94\x01\x12\x15\n\x11SID_LOL_MATCH_REQ\x10\x08\x12\x15\n\x11SID_LOL_MATCH_RES\x10\tb\x06proto3')
  ,
  dependencies=[nana_dot_esports_dot_lol_dot_match__pb2.DESCRIPTOR,])

_LOLMATCHSVRID = _descriptor.EnumDescriptor(
  name='LolMatchSvrID',
  full_name='nana.biz.lol.LolMatchSvrID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SID_LOL_MATCH_UNKNOW', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SID_LOL_MATCH_HEARTBEAT_REQ', index=1, number=2305,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SID_LOL_MATCH_HEARTBEAT_RES', index=2, number=2306,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SID_LOL_MATCH_RESTART_REQ', index=3, number=2307,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SID_LOL_MATCH_RESTART_RES', index=4, number=148,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SID_LOL_MATCH_REQ', index=5, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SID_LOL_MATCH_RES', index=6, number=9,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=294,
  serialized_end=513,
)
_sym_db.RegisterEnumDescriptor(_LOLMATCHSVRID)

LolMatchSvrID = enum_type_wrapper.EnumTypeWrapper(_LOLMATCHSVRID)
SID_LOL_MATCH_UNKNOW = 0
SID_LOL_MATCH_HEARTBEAT_REQ = 2305
SID_LOL_MATCH_HEARTBEAT_RES = 2306
SID_LOL_MATCH_RESTART_REQ = 2307
SID_LOL_MATCH_RESTART_RES = 148
SID_LOL_MATCH_REQ = 8
SID_LOL_MATCH_RES = 9



_LOLMATCHREQ = _descriptor.Descriptor(
  name='LolMatchReq',
  full_name='nana.biz.lol.LolMatchReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='nana.biz.lol.LolMatchReq.time', index=0,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='match', full_name='nana.biz.lol.LolMatchReq.match', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=142,
)


_LOLMATCHRES = _descriptor.Descriptor(
  name='LolMatchRes',
  full_name='nana.biz.lol.LolMatchRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='nana.biz.lol.LolMatchRes.code', index=0,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='match', full_name='nana.biz.lol.LolMatchRes.match', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=214,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='nana.biz.lol.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='nana.biz.lol.Request.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='nana.biz.lol.Request.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=253,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='nana.biz.lol.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='nana.biz.lol.Result.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='nana.biz.lol.Result.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=291,
)

_LOLMATCHREQ.fields_by_name['match'].message_type = nana_dot_esports_dot_lol_dot_match__pb2._LOLMATCH
_LOLMATCHRES.fields_by_name['match'].message_type = nana_dot_esports_dot_lol_dot_match__pb2._LOLMATCH
DESCRIPTOR.message_types_by_name['LolMatchReq'] = _LOLMATCHREQ
DESCRIPTOR.message_types_by_name['LolMatchRes'] = _LOLMATCHRES
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.enum_types_by_name['LolMatchSvrID'] = _LOLMATCHSVRID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LolMatchReq = _reflection.GeneratedProtocolMessageType('LolMatchReq', (_message.Message,), dict(
  DESCRIPTOR = _LOLMATCHREQ,
  __module__ = 'nana.biz.lol.match_pb2'
  # @@protoc_insertion_point(class_scope:nana.biz.lol.LolMatchReq)
  ))
_sym_db.RegisterMessage(LolMatchReq)

LolMatchRes = _reflection.GeneratedProtocolMessageType('LolMatchRes', (_message.Message,), dict(
  DESCRIPTOR = _LOLMATCHRES,
  __module__ = 'nana.biz.lol.match_pb2'
  # @@protoc_insertion_point(class_scope:nana.biz.lol.LolMatchRes)
  ))
_sym_db.RegisterMessage(LolMatchRes)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'nana.biz.lol.match_pb2'
  # @@protoc_insertion_point(class_scope:nana.biz.lol.Request)
  ))
_sym_db.RegisterMessage(Request)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'nana.biz.lol.match_pb2'
  # @@protoc_insertion_point(class_scope:nana.biz.lol.Result)
  ))
_sym_db.RegisterMessage(Result)


# @@protoc_insertion_point(module_scope)
